#!/usr/bin/env bash
set -euo pipefail

REPOSITORY_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
PROJRES_PYTHON_BIN="${PROJRES_PYTHON:-python}"
PROJRES_CONFIG_PATH="${PROJRES_CONFIG:-configs/federated_prompt_paper.yaml}"
PROJRES_OUTPUT_ROOT="${PROJRES_RESULTS_DIR:-results/projres_validation}"
PROJRES_DATASET_NAME="${PROJRES_DATASET:-caltech101}"
PROJRES_DATA_ROOT_PATH="${PROJRES_DATA_ROOT:-./data}"
PROJRES_CACHE_ROOT_PATH="${PROJRES_CACHE_DIR:-./checkpoints/clip-vit-base-patch32}"
PROJRES_BATCH_SIZE_VALUE="${PROJRES_BATCH_SIZE:-16}"
PROJRES_LEARNING_RATE_VALUE="${PROJRES_LEARNING_RATE:-0.0001}"
PROJRES_CONTEXT_LENGTH="${PROJRES_N_CTX:-16}"
PROJRES_LOCAL_STEP_COUNT="${PROJRES_LOCAL_STEPS:-1}"
PROJRES_CANDIDATE_COUNT="${PROJRES_MAX_CANDIDATES:-128}"
PROJRES_SEED_VALUE="${PROJRES_SEED:-42}"
PROJRES_TARGET_CLIENT_VALUE="${PROJRES_TARGET_CLIENT:-all}"

cd "$REPOSITORY_ROOT"
mkdir -p "$PROJRES_OUTPUT_ROOT"

exec "$PROJRES_PYTHON_BIN" \
  scripts/validate_projres_promptfl_real.py \
  --config "$PROJRES_CONFIG_PATH" \
  --dataset-name "$PROJRES_DATASET_NAME" \
  --data-root "$PROJRES_DATA_ROOT_PATH" \
  --cache-dir "$PROJRES_CACHE_ROOT_PATH" \
  --batch-size "$PROJRES_BATCH_SIZE_VALUE" \
  --learning-rate "$PROJRES_LEARNING_RATE_VALUE" \
  --n-ctx "$PROJRES_CONTEXT_LENGTH" \
  --local-steps "$PROJRES_LOCAL_STEP_COUNT" \
  --max-candidates "$PROJRES_CANDIDATE_COUNT" \
  --seed "$PROJRES_SEED_VALUE" \
  --target-client "$PROJRES_TARGET_CLIENT_VALUE" \
  --ridge 1e-4 \
  --lift-iterations 20 \
  --lift-tolerance 1e-5 \
  --output "$PROJRES_OUTPUT_ROOT/${PROJRES_DATASET_NAME}_${PROJRES_TARGET_CLIENT_VALUE}_b${PROJRES_BATCH_SIZE_VALUE}_steps${PROJRES_LOCAL_STEP_COUNT}.json" \
  "$@"
